language: smalltalk
dist: Xenial

os: linux

smalltalk:
  - GemStone-3.2.15
  - GemStone-3.3.1
  - GemStone-3.3.9
  - GemStone-3.4.5
  - GemStone-3.5.3

cache:
  directories:
    - $SMALLTALK_CI_CACHE

notifications:
  slack: gemtalksystems:ENb7sBznQr32ZxlOCAdFfZdm
